# This workflow runs on a `push` to any branch

name: all push -- CI

on:
  push:
    branches:
      - '*'

jobs:
  # Lint and type checking
  lint_and_type_check:
    name: Lint and type check
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          pip install pre-commit
      - name: Lint and type check
        run: |
          pre-commit run --all-files --verbose --show-diff-on-failure

  # Unit test and coverage
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install package with dependencies
        run: |
          pip install .[tests]
      - name: Test with pytest
        run: |
          # grab the coverage output and also print it to the sreen
          COVERAGE_REPORT=$(coverage run -m pytest && coverage report -m | \
            tee /dev/stderr)
          # extract the percentage of the total coverage, e.g. `75%`
          COVERAGE_PCT=$(echo $COVERAGE_REPORT | \
            grep -oP "TOTAL\s+\d+\s+\d+\s+(\d+%)" | grep -oP "\d+%")
          # get an indicative color
          COVERAGE_NUM=$(echo $COVERAGE_PCT | grep -oP "\d+")
          if (( COVERAGE_NUM <= 50 )); then
            COVERAGE_COL="red"
          elif (( COVERAGE_NUM <= 60 )); then
            COVERAGE_COL="orange"
          elif (( COVERAGE_NUM <= 70 )); then
            COVERAGE_COL="yellow"
          elif (( COVERAGE_NUM <= 80 )); then
            COVERAGE_COL="yellowgreen"
          elif (( COVERAGE_NUM <= 90 )); then
            COVERAGE_COL="green"
          else
            COVERAGE_COL="brightgreen"
          fi
          # active branch name
          echo "yup"
          echo "${GITHUB_REF#refs/heads/}"
          BRANCH_NAME=$(echo ${GITHUB_REF#refs/heads/})
          echo $BRANCH_NAME
          # add them to the github env for later usage
          echo "COVERAGE_PCT=$(echo $COVERAGE_PCT)" >> $GITHUB_ENV
          echo "COVERAGE_COL=$(echo $COVERAGE_COL)" >> $GITHUB_ENV
          echo "BRANCH_NAME=$(echo $BRANCH_NAME)" >> $GITHUB_ENV

      - name: Upload coverage to gist
        uses: schneegans/dynamic-badges-action@v1.1.0
        with:
          auth: ${{ secrets.GIST_SECRET }}
          gistID: da9e3419b54a0daf6fe07b934f37f837
          filename: zandbak_${{ env.BRANCH_NAME }}_coverage.json
          label: coverage
          message: ${{ env.COVERAGE_PCT }}
          color: ${{ env.COVERAGE_COL }}
